export const ASCENDING_ORDER = 'ASCENDING';
export const DESCENDING_ORDER = 'DESCENDING';
export const ALPHABETICAL_ORDER = 'ALPHABETICAL';
export const DIFFICULTY_ORDER = 'DIFFICULTY';
export const DEFAULT_ORDER = ASCENDING_ORDER;

export const CHANGE_THEME = 'CHANGE_THEME';