# Generated by Django 5.0.7 on 2024-08-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intervals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervaltemplate',
            name='user',
        ),
    ]
