# Generated by Django 5.0.7 on 2024-08-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervals', '0002_remove_intervaltemplate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervaltemplate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
