# Generated by Django 5.0.7 on 2024-08-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studys', '0002_studiedrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studiedrecord',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='studiedrecord',
            name='learn_time',
            field=models.DateField(null=True),
        ),
    ]
