# Generated by Django 5.0.7 on 2024-08-08 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studys', '0004_rename_studiedrecord_reviewstudy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewstudy',
            old_name='learn_time',
            new_name='review_time',
        ),
        migrations.AddField(
            model_name='study',
            name='study_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
