# Generated by Django 5.0.7 on 2024-08-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studys', '0005_rename_learn_time_reviewstudy_review_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='study_time',
            field=models.DateField(null=True),
        ),
    ]
