# Generated by Django 5.0.7 on 2024-08-08 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studys', '0007_alter_study_study_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='study_time',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
