# Generated by Django 5.0.7 on 2024-08-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studys', '0012_alter_reviewstudy_review_time_alter_study_study_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewstudy',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
