export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const LOGOUT = "LOGOUT";
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

//new item
export const ADD_LEARN_ACTION = "ADD_LEARN_TASK";
export const ADD_LEARNS_ACTION = "ADD_LEARNS_TASK";
export const SET_LEARNS_ACTION = "SET_LEARNS_TASK";
export const DELETE_LEARN_ACTION = "DELETE_LEARN_TASK";
export const UPDATE_LEARN_ACTION = "UPDATE_LEARN_TASK";
export const UPDATE_LEARN_DIFFICULTY = "UPDATE_LEARN_DIFFICULTY";

//review item 
export const ADD_REVIEW_ACTION = "ADD_REVIEW_TASK";
export const DELETE_REVIEW_ACTION = "DELETE_REVIEW_TASK";
export const UPDATE_REVIEW_ACTION = "UPDATE_REVIEW_TASK";
export const SET_REVIEWS_ACTION = "SET_REVIEWS_TASK";

export const SEARCH_ACTION = "SEARCH";
export const ADD_FILTER_ACTION = "ADD_FILTER";
export const REMOVE_FILTER_ACTION = "REMOVE_FILTER";
export const CLEAR_FILTER_ACTION = "CLEAR_FILTER";
export const SET_SORT_ACTION = "SET_SORT";
export const SET_PAGE_ACTION = "SET_PAGE";

export const TOGGLE_LOGIN_FORM = "TOGGLE_LOGIN_FORM";
export const TOGGLE_REGISTER_FORM = "TOGGLE_REGISTER_FORM";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const TOGGLE_MODAL = "TOGGLE_MODAL";

export const CHANGE_DATE = "CHANGE_DATE";
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";

export const SET_SETTINGS = "SET_SETTINGS";

export const INCREASE_TEMP_ID = "INCREASE_TEMP_ID";
export const DECREASE_TEMP_ID = "DECREASE_TEMP_ID";
export const RESEt_TEMP_ID = "RESET_TEMP_ID";

export const SET_FILTERS_ID = "SET_FILTERS_ID";